# https://huggingface.co/docs/autotrain/en/quickstart
name: hf-autotrain
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch-cuda=12.1 # requires nvidia::cuda-cudart
  - nvidia/label/cuda-12.1.0::cuda-nvcc
  - xformers::xformers
  - pip
  - pip:
    - ipykernel # Must be specified for .devcontainers to work correctly
    - notebook # Must be specified for .devcontainers to work correctly
    - ipywidgets
    - matplotlib
    - numpy
    - pandas
    - scipy
    - torch-summary
    - tensorboard
    - autotrain-advanced
    - mlflow
